### PR TITLE
Prop for foreground extrapolation

### PR DESCRIPTION
**Pull request by rostislav-simonik**
When you want to uses picture title with bottom position as foreground component, then extrapolation should be present when header is grown (clamp mode is not desired in that case). So for that case I've introduced property that allows override default clamp extrapolation for foreground component.

### CODE REVIEW

**Comment by Nhacsam** [comment]
Thanks @rostislav-simonik, looks nice !

Can you add some documentation in README before I merge ?

**Comment by rostislav-simonik** [comment]
> Thanks @rostislav-simonik, looks nice !
> 
> Can you add some documentation in README before I merge ?

Done.

**Comment by Nhacsam** [comment]
Thanks

**Comment by Nhacsam** [comment]
Published : https://github.com/bamlab/react-native-image-header-scroll-view/releases/tag/0.10.2

**Pull request merged**
